slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frames / topics
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    mode: mapping

    # General
    throttle_scans: 1
    transform_publish_period: 0.02
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 8.0
    minimum_time_interval: 0.0

    # Loop closure / scan matching (başlangıç için güvenli)
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    scan_matching: true
